### ISSUE TITLE
Unwrap else causes both branches to be displayed

### ISSUE THREAD

**Issue by wombat2k** [vapor-community/HTMLKit#108]
Hello,

I'm still trying to get to grips with this library, but I think I might possibly have hit a bug.

In the example below (re-structured to make it easier to reproduce), you will see that I call a route with a parameter of `name` which is passed as an optional `String` in the struct.

When I call `Unwrap`, I get the expected output, but in addition, I also get the output from the else branch

<img width="197" alt="Screenshot 2022-11-27 at 11 50 42 AM" src="https://user-images.githubusercontent.com/497372/204148953-386208a2-6f51-4a47-97d9-17e274e65016.png">

```swift
import Vapor
import HTMLKit
import HTMLKitVapor

struct SimpleContext: Codable {
    let name: String?
}

struct SimpleView: HTMLKit.View {
    @TemplateValue(SimpleContext.self)
    var context
    
    var body: AnyContent {
        Unwrap(context.name) { name in
            Heading1 {
                "Hello " + name + "!"
            }
        }.else {
            Heading1 {
                "Hello, World!"
            }
        }
    }
}

func routes(_ app: Application) throws {
    app.get("hello", ":name") { req async throws -> Vapor.View in
        req.application.htmlkit.views.add(view: SimpleView())
        let name = req.parameters.get("name")
        let context = SimpleContext(name: name)
        
        return try await req.view.render("App.SimpleView", context)
    }
}
```

**Comment by mattesmohr** [comment]
Yup, I think you have encountered a bug. The else branch ohne the Unwrap statement is not from me, thats why I have never considered writing a test for it. I also will deprecated it for version 2.9, since I think of it more like a `guard let` statement and not a conditional statement.

But yes, let me check if I can write a fix for it.

**Comment by mattesmohr** [comment]
Okay, the bug seems to affect more than just only the Unwrap statement. Thanks for reaching out.
