### ISSUE TITLE
Ambiguous use of 'buildBlock'

### ISSUE THREAD

**Issue by tonyarnold** [vapor-community/HTMLKit#132]
I'm seeing quite a few instances where I use an `if let` unwrap within the body of a View where Swift can't make up it's mind about which method to use: 

For instance: 

```swift
Nav {
  Anchor { … }

  if let authenticatedUser = context.authenticatedUser {
    Div { … }
  }
}
```

results in: 

```
HeaderViewComponent.swift:48:74: error: ambiguous use of 'buildBlock'
                    if let authenticatedUser = context.authenticatedUser {
                                                                         ^
HTMLKit/Sources/HTMLKit/Framework/Builders/ContentBuilder.swift:41:24: note: found this candidate
    public static func buildBlock(_ components: T...) -> [T] {
                       ^
HTMLKit/Sources/HTMLKit/Framework/Builders/ContentBuilder.swift:121:24: note: found this candidate
    public static func buildBlock(_ content: [T], _ components: T...) -> [T] {
```

**Comment by mattesmohr** [comment]
Oh true, this one. I have encountered it multiple times too, but I couldn't fixed without breaking other things. I went nuts. 

I was hoping I come up with an idea someday. 

I wanted to tackle this one after I am done with the components, but let me see if I can fix it at the weekend for good.

Maybe the new changes for the result builder and new parameter packs, can help me with that.

**Comment by mattesmohr** [comment]
If I recall correctly, the result builder doesn't like it that way:

```swift
Nav {
  Anchor { … }

  if let authenticatedUser = context.authenticatedUser {
    Div { … }
  }
}
```

But the opposite way is fine:

```swift
Nav {
  if let authenticatedUser = context.authenticatedUser {
    Div { … }
  }

  Anchor { … }
}
```

So what I did in the moment, is wrapping the if statement in another element.

```swift
Nav {
  Div {
      if let authenticatedUser = context.authenticatedUser {
         Div { … }
      }
 }

  Anchor { … }
}
```

Hope it helps, till I found a solution. Fingers crossed.

**Comment by tonyarnold** [comment]
I'm seeing the same thing for an if statement at the root of a body. Is there a workaround for that that you know about? (I don't want the body to render anything unless a certain condition is met).

**Comment by mattesmohr** [comment]
Oh, that's new to me. But I suspect it has something to do, that Body expects a result of [BodyElement]. And the statement returns  [Content]. 

Use the Custom as a workaround. 

```swift
Custom(name: "body") {
}
```

I will open a issue for it separately.

**Comment by mattesmohr** [comment]
Should be fixed by now. I close the issue.
