### ISSUE TITLE
How to pass-through attributes to custom components?

### ISSUE THREAD

**Issue by jpenwith** [vapor-community/HTMLKit#151]
I have a component for an html <input /> element:

```
struct EmailAddressInput: HTMLKit.View {
  let name: String
  let value: String
  let disabled: Bool

  init(name: String = "email_address", value: String = "", disabled: Bool = false) {
    self.name = name
    self.value = value
    self.disabled = disabled
  }

  var body: any Content {
    Input()
      .type(.email).name(name).value(value)
      .placeholder("Your email address")
      .required().maximum(length: 256)
      .disabled(disabled)
      .custom(key: "autocomplete", value: "username")
      .id("email_address")
  }
}
```

If I then use:

`EmailAddressInput(name: "email_address")`

HTMLKit will render:

```
<input type="email" name="email_address" value="" placeholder="Your email address" required="required" maxlength="256" autocomplete="username" id="email_address">
```

How do I pass through a class attribute to this component, i.e. how do I enable this:

`EmailAddressInput(name: "email_address").class("centered red-text")`

to render this:

`<input type="email" name="email_address" value="" placeholder="Your email address" required="required" maxlength="256" autocomplete="username" id="email_address" class="centered red-text">`

I've had a look at conforming to `ClassAttribute` but I can't access `mutate` as it's internal. Could you give a pointer on how to achieve this

Fantastic framework by the way, I love writing HTML like this!

**Comment by mattesmohr** [comment]
Hey @jpenwith,

I am happy to hear the framework is useful to you. You are right, the ClassAttribute protocol is only for the html abstraction so to say. But what you can do instead - and also I do the same for the HTMLKitComponents:


```swift
struct EmailAddressInput: HTMLKit.View {
  let name: String
  let value: String
  let disabled: Bool
  var classes: [String] // 1.

  init(name: String = "email_address", value: String = "", disabled: Bool = false) {
    self.name = name
    self.value = value
    self.disabled = disabled
    self.classes = [] // 2.
  }

  var body: any Content {
    Input()
      .type(.email).name(name).value(value)
      .placeholder("Your email address")
      .required().maximum(length: 256)
      .disabled(disabled)
      .custom(key: "autocomplete", value: "username")
      .id("email_address")
      .class(classes.joined(separator: " ")) // 3.
  }
  
  // 4.
  func class(_ value: String) -> EmailAddressInput {
     
     var copy = self
     self.classes.append(value)
     
     return self
  }
}
```

Does that help you? Let me know.

**Comment by jpenwith** [comment]
That's great, thanks. Appreciate the response 👍
