### ISSUE TITLE
<img> support for HTML initialiser

### ISSUE THREAD

**Issue by bdgeyter** [vapor-community/HTMLKit#22]
While I was trying out adding an image from a TemplateValue, I can't seem to find a way to initialise that easily. 

Would it make sense to add an overload which would allow:
```swift
struct Movie {
    let poster: URL
}

struct MovieTemplate {
    @TemplateValue(Movie.self)
     var movie

    var body: HTML {
         Img(source: movie.poster.absoluteString)
    }
}
```

Additionally, was also wondering if it would make sense to have`URL` conform to `HTML`. 

Happy to contribute, but wanted to reach out first to get more context.

**Comment by MatsMoll** [comment]
Hi! 
Thanks for the issue. I will push an update with a new initiliser that can take a `TemplateValue`.

About conforming `URL` to `HTML`. I am guessing that would mean the `.absoluteString` value is rendered? Or was you thinking that it tried to be smart an insert an image or anchor?

**Comment by bdgeyter** [comment]
Awesome, thanks! 🙏 

For `URL` I was indeed thinking for now on simple conformance using `.absoluteString`, so it can be easily passed in `Img` or `Link` structs. 

```swift
extension URL: HTML {

    // View `HTML` documentation
    public func render<T>(with manager: HTMLRenderer.ContextManager<T>) throws -> String {
        return self.absoluteString
    }

    // View `HTML` documentation
    public func prerender(_ formula: HTMLRenderer.Formula) throws {
        formula.add(string: self.absoluteString)
    }
}
```

I indeed wouldn't make it too smart by assuming Img or Link, as URLs are valuable in other places in HTML. Potentially fancier, the URL type information could be used to auto-escape where appropriate, and deliver built in safety 🤔,  but definitely wasn't my first thought.

**Comment by bdgeyter** [comment]
I'll send over a PR this weekend.

**Comment by MatsMoll** [comment]
Sounds good! I do not know if it can propagate to some odd behavior, but you want to create a pull request either just for the conformance or something fancier? 
That way you can get the credit for contributing 🤩

**Comment by MatsMoll** [comment]
> I'll send over a PR this weekend.

Awesome 🤩

**Comment by MatsMoll** [comment]
Should be released a new version containing the new init now
