### ISSUE TITLE
Provide example in the README to what to do in the controller to render something

### ISSUE THREAD

**Issue by renaudjenny** [vapor-community/HTMLKit#24]
Hi There,

I'm really sorry, but I don't understand how this framework works.
I tried to render an `HTMLTemplate` but firstly it's not clear to how and what you should call in your controllers.

I tried that:
```swift
    func get(req: Request) throws -> EventLoopFuture<View> {
        guard
        let groomingSessionIdString = req.parameters.get("groomingSessionID"),
        let groomingSessionId = UUID(uuidString: groomingSessionIdString)
        else {
            return req.eventLoop.makeFailedFuture(Abort(.badRequest))
        }

        return GroomingSession.query(on: req.db)
            .filter(\.$id == groomingSessionId)
            .with(\.$userStories)
            .first()
            .unwrap(or: Abort(.notFound))
            .flatMapThrowing {
                let renderer = HTMLRenderer()
                try renderer.add(view: GroomingSessionTemplate())
                let context = GroomingSessionData(groomingSession: $0)
                let data = ByteBuffer(string: try renderer.render(raw: GroomingSessionTemplate.self, with: context))
                return View(data: data)
            }
    }
```

And that's the closer I can get to have something rendered, but I got `Grooming Session: dynamic(HTMLKit.HTMLContext)` instead of the results of what I want, in this case `H1 { "Grooming Session: \(context.groomingSession.name)" }`, so I'm quite sure that I'm **not** doing this well. However there is no concrete example in the README 😞. I'm lost...

I put a comment in #21 as it's more or less related I think.

Thanks!

**Comment by MatsMoll** [comment]
Thanks for the feedback!

The code you are using to render the template is correct. However, I would recommend making the renderer instance global in some way. As it will keep the prerendered template in memory and therefore lead to faster rendering time. This [repo](https://github.com/MatsMoll/htmlkit-vapor-provider) can do it for you. It is not well documented, unfortunately, but you can do `req.htmlkit.render(...)` or `app.htmlkit.add(...)`.

When it comes to the template result. As of now do HTMLKit not support string interpolation, so you have to do something like:
```swift
H1 { 
    "Grooming Session: " 
    context.groomingSession.name
}

// or
H1 {  "Grooming Session: " + context.groomingSession.name }
```
I will also check the comment issue created tomorrow and try to add some more examples in order to make it easier to understand the framework.

**Comment by renaudjenny** [comment]
Thanks for the answer @MatsMoll, unfortunately I still miss a step. But I'm feeling very close to have a result soon 😆.
When importing `.package(url: "https://github.com/MatsMoll/htmlkit-vapor-provider.git", from: "1.0.0-beta.3")` in my `Package.swift`, and doing `.product(name: "HTMLKitVaporProvider", package: "htmlkit-vapor-provider"),` Packager complains about
```
/Users/renaudjenny/Sources/SteamScrum/Package.swift: product dependency 'HTMLKitVaporProvider' in package 'htmlkit-vapor-provider' not found
```
If I just comment the `.product(...)` line, it's ok, but impossible for my `configure.swift` to know that `Application` has an extension allowing me to do `app.htmlkit.add(...)`: `Value of type 'Application' has no member 'htmlkit'`.

I think I'm doing something wrong inside my `Package.swift` but I can't figure it out what 🥺.

I'm sorry to be such a pain, but I can't wait to see this working 😄, I'm very enthusiastic about this library, it's very promising!

**Comment by MatsMoll** [comment]
No problem, and thanks for the enthusiastic response 😄

I think the problem will solve itself by changing the package from `1.0.0-beta.3` to `1.0.0-beta.4`. I am also using `.product(name: "HTMLKitVaporProvider", package: "HTMLKitVaporProvider")` as the product.

Let me know if you need any more help.

**Comment by renaudjenny** [comment]
I'm sorry, still not working 😞.
Here is my `Package.swift`:
```
// swift-tools-version:5.2
import PackageDescription

var dependencies: [PackageDescription.Package.Dependency] = [
    .package(url: "https://github.com/vapor/vapor.git", from: "4.0.0"),
    .package(url: "https://github.com/vapor/fluent.git", from: "4.0.0"),
    .package(url: "https://github.com/vapor/fluent-postgres-driver.git", from: "2.0.0"),
    .package(url: "https://github.com/vapor-community/HTMLKit.git", from: "2.0.0-beta.3"),
    .package(url: "https://github.com/MatsMoll/htmlkit-vapor-provider.git", from: "1.0.0-beta.4"),
]

#if os(macOS)
dependencies.append(.package(url: "https://github.com/vapor/fluent-sqlite-driver", from: "4.0.0"))
#endif

var appTargetDependencies: [PackageDescription.Target.Dependency] = [
    .product(name: "Fluent", package: "fluent"),
    .product(name: "FluentPostgresDriver", package: "fluent-postgres-driver"),
    .product(name: "Vapor", package: "vapor"),
    .product(name: "HTMLKit", package: "HTMLKit"),
    .product(name: "HTMLKitVaporProvider", package: "HTMLKitVaporProvider"),
]

#if os(macOS)
appTargetDependencies.append(.product(name: "FluentSQLiteDriver", package: "fluent-sqlite-driver"))
#endif

let package = Package(
    name: "SteamScrum",
    platforms: [
       .macOS(.v10_15)
    ],
    dependencies: dependencies,
    targets: [
        .target(
            name: "App",
            dependencies: appTargetDependencies,
            swiftSettings: [
                // Enable better optimizations when building in Release configuration. Despite the use of
                // the `.unsafeFlags` construct required by SwiftPM, this flag is recommended for Release
                // builds. See <https://github.com/swift-server/guides#building-for-production> for details.
                .unsafeFlags(["-cross-module-optimization"], .when(configuration: .release))
            ]
        ),
        .target(name: "Run", dependencies: [.target(name: "App")]),
        .testTarget(name: "AppTests", dependencies: [
            .target(name: "App"),
            .product(name: "XCTVapor", package: "vapor"),
        ]),
    ]
)
```
Compile says: `/Users/renaudjenny/Sources/SteamScrum/Package.swift: unknown package 'HTMLKitVaporProvider' in dependencies of target 'App'`

If I change `.product(name: "HTMLKitVaporProvider", package: "htmlkit-vapor-provider")` it says: `/Users/renaudjenny/Sources/SteamScrum/Package.swift: product dependency 'HTMLKitVaporProvider' in package 'htmlkit-vapor-provider' not found`

Which is a bit different, but in the `HTMLKitVaporProvider` I saw that `'HTMLKitVaporProvider'` is well named and everything, so I tried that: `.package(name: "HTMLKitVaporProvider", url: "https://github.com/MatsMoll/htmlkit-vapor-provider.git", from: "1.0.0-beta.4"),` a.k.a explicitly providing the package name, **and it works!**.

Thanks again! I could quickly fix the README of the other repo with a PR if you want? Just tell me ;).

I will do a PR on this repo as well to improve the README and help future user to enjoy this awesome library at first try 😄.

**Comment by MatsMoll** [comment]
Good you made it work in the end. And I would be grateful for some pull requests in order to improve the readmes 😄
