### ISSUE TITLE
Missing some HTML-Tags

### ISSUE THREAD

**Issue by mattesmohr** [vapor-community/HTMLKit#28]
Heya @MatsMoll,

I miss some current HTML-Tags in HTMLKit. Is it on purpose? Or are you interested in some help here?

Let me know.

**Comment by MatsMoll** [comment]
Thanks for adding the main tag, and if you feel like adding more, then continue adding them! All help will be appreciated

**Comment by MatsMoll** [comment]
Btw, now will a new release of the latest master version automatically be released. So add all the changes you want!
