### ISSUE TITLE
Deprecated documentation

### ISSUE THREAD

**Issue by adamnagydev** [vapor-community/HTMLKit#50]
Hi! 👋

I really like the implementation of HTMLKit, but it seems the documentation is kind of deprecated now. 
I'm really new with Vapor and want to use this framework, but it's hard to figure out a lot of things as I can't rely on the documentation. 

Is it possible to get an update in the near future?

**Comment by mattesmohr** [comment]
Hey @adamnagydev, happy to hear you like it. The last couple weeks I have changed a lot. And I wanted to get sure to have a solid code before updating the documentation. 

I am on it! Promise! 

It is coming with the next release. Sorry for the inconvenience.

**Comment by adamnagydev** [comment]
Hey @mattesmohr ! 

Thank you for that, I really appreciate it and looking forward to it! :)

**Comment by adamnagydev** [comment]
Hey @mattesmohr ! 

Thank you for that, I really appreciate it and looking forward to it! :)
