### ISSUE TITLE
2.4.0 - Known issues

### ISSUE THREAD

**Issue by mattesmohr** [vapor-community/HTMLKit#53]
I use HTMLKit 2.4.0 in my projects and so far I encounter some issues. I list them here, so so you know I am aware of them and they will get fixed very soon.

The alternate attribute gets rendered as `alternate=""` instead of `alt=""`.

The link element is `BodyElement` instead of a `HeadElement`. Quick workaround, till I release a fix:

```swift
extension Link: HeadElement {}
```

The `ForEach` should be a `GlobalElement`.

**Comment by mattesmohr** [comment]
The issues from before should be fixed with 2.4.1.

**Comment by adamnagydev** [comment]
Please check internal protected properties and values, because lots of them are not public yet.

What I've found so far: 
- NameTypes
- Meta OrderedDictionary init

**Comment by adamnagydev** [comment]
Script is not a head element and can't access the dictionary version of the init.

**Comment by mattesmohr** [comment]
> 
> Please check internal protected properties and values, because lots of them are not public yet.
> 

What do you mean by that? The attribute dictionary in an element is protected and declared as internal on purpose.

**Comment by mattesmohr** [comment]
Also some issues I am encounter:
- The http-equiv attribute is missing.
- The charset attribute is missing.

**Comment by mattesmohr** [comment]
The issues from before should be fixed with 2.4.2.

@adamnagydev Also I have added a custom attribute now. Take a look here #59, if it helps you with your problem.

**Comment by adamnagydev** [comment]
Thank you for the great suggestions @mattesmohr ! Not I got the gist, it helped a lot. :) 

Also, can't wait for the upcoming releases. Super great progress and package!
