### ISSUE TITLE
Target behavior

### ISSUE THREAD

**Issue by Kyle-Ye** [vapor-community/HTMLKit#68]
When use the following code
```swift
Anchor { "Site" }.reference("/").target(.blank)
```
I thought I'll get the corresponding HTML code
```
<a href="/" target="_blank">Site</a>
```
Instead I get this. Is it the intended behavior? 
```html
<a href="/" type="blank">Site</a>
```

And what should I do if I'd like to open link in a new tab in HTMLKit?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target

**Comment by mattesmohr** [comment]
Nope, you are right. That's a mistake. It should be "_blank". 

I will write a fix.

**Comment by Kyle-Ye** [comment]
Actually, there is another bug needs to be fixed. (In the Anchor's mutate method see #70)
