### ISSUE TITLE
renderIf(…) is ambiguous without more context

### ISSUE THREAD

**Issue by tonyarnold** [vapor-community/HTMLKit#7]
Hi, thanks for this project - it seems really promising!

I'm using HTMLKit 1.3.0 in a Vapor 3.x project. 

I've hit an issue where I have a template component (my site's navigation) that I'd like to render differently depending on specific parameters, so I've created the following struct:

```swift
struct NavigationView: StaticView {
    let route: String
    let organization: Organization?

    func build() -> CompiledTemplate {
        return nav.add(.id("navigation")).child(
            ul.class("links").child(
                renderNavigationLinks()
            )
        )
    }

    func renderNavigationLinks() -> CompiledTemplate {
        return
            renderIf(\.route == "administration", administrationNavigationItems()) +
            renderIf(\.route == "organization", organizationNavigationItems()) +
            renderIf(\.route == "personal", personalNavigationItems())
    }

    func administrationNavigationItems() -> CompiledTemplate {
        // …
    }

    func organizationNavigationItems() -> CompiledTemplate {
        // …
    }

    func personalNavigationItems() -> CompiledTemplate {
        // …
    }
}
```

However, I then get the following error:

```
Type of expression is ambiguous without more context
```

Swift appears to be struggling to differentiate between the following two methods:

https://github.com/vapor-community/HTMLKit/blob/50adfa25680b7597679175cad657c96352498b12/Sources/HTMLKit/Protocols/ContextualTemplate.swift#L55-L58

https://github.com/vapor-community/HTMLKit/blob/50adfa25680b7597679175cad657c96352498b12/Sources/HTMLKit/Protocols/ContextualTemplate.swift#L66-L70

**Comment by MatsMoll** [comment]
Hi @tonyarnold and thanks for the feedback!

The reason for the error is that `renderIf` is expecting a `Context` and in your case there are non since you are using a `StaticView`. This is currently a limitation in HTMLKit 1, but this will be solved in HTMLKit 2.
So you need to convert to a `ContextualTemplate` and wrap the `route: String` in a `Context` struct. Or you could convert to a alpha version of HTMLKit 2 that supports Vapor 3.x. This would require Swift 5.1 and I would need to upload this to a branch if it this is a more appealing option.

**Comment by MatsMoll** [comment]
Btw. HTMLKit 2 require a big rewrite, as it similar to SwiftUI. But I have written a small playground that simplifies the transition from HTMLKit 1 code into HTMLKit 2.

**Comment by tonyarnold** [comment]
> So you need to convert to a ContextualTemplate and wrap the route: String in a Context struct. 

That's exactly what I'll do, thanks!

> Or you could convert to a alpha version of HTMLKit 2 that supports Vapor 3.x. This would require Swift 5.1 and I would need to upload this to a branch if it this is a more appealing option.

Nah, please don't on my account - keep focusing on the new stuff for Vapor 4 - time and energy is a limited thing. Thanks again for the great library!

**Comment by MatsMoll** [comment]
Btw. I actually needed the Vapor 3 support my self, so it is possible to use HTMLKit 2 with the branch at [vapor-3-support](https://github.com/vapor-community/HTMLKit/tree/vapor-3-support).
