### ISSUE TITLE
RawValue for optional value

### ISSUE THREAD

**Issue by Kyle-Ye** [vapor-community/HTMLKit#71]
The rawValue implementation is call description method
```swift
case .constant(let value): return "\(value)"
default: return ""
}
```
So if a TemplateValue<Value>'s Value is an Optional type, it's result will surprisingly be "Optional(xx)"  

A example is the following
> id is `UUID?` type and a property in Post model
> post is `TemplateValue<Post>` here
```
A { "Hello" }.id(post.id.rawValue)
```
This will give me "Optional(xx)" or "nil".
But what I want is "xx" or "".
However I can't do it, since I can not get a `Post` type or `UUID?` here.
All I can get is `TemplateValue<Post>` and `TemplateValue<UUID?>` and then call the rawValue method.

**Comment by Kyle-Ye** [comment]
A potential solution is to support for..in loop directly in result Builder. See #72 

So that we can write
```swift
Tbody {
    for post in posts {
        Tr {
           H1 { post.title }.id(post.id?.uuidString ?? "")
        }
    }
}
```

**Comment by mattesmohr** [comment]
Not sure, what you trying to do. But the native statements are not possible at the moment. The same as we have discussed in the issue #61. 

Would the statements [Unwrap and Foreach](https://github.com/vapor-community/HTMLKit/blob/main/Instructions/Essential/Statements.md) help in your case?

**Comment by Kyle-Ye** [comment]
> Not sure, what you trying to do. But the native statements are not possible at the moment. The same as we have discussed in the issue #61.
> 
> Would the statements [Unwrap and Foreach](https://github.com/vapor-community/HTMLKit/blob/main/Instructions/Essential/Statements.md) help in your case?

Got it, `Unwrap` is what I need. Thanks
