### ISSUE TITLE
How to use the examples provded on your main page?

### ISSUE THREAD

**Issue by patchthecode** [vapor-community/HTMLKit#8]
The following is my code with the errors

<img width="710" alt="Screen Shot 2019-11-12 at 8 09 52 PM" src="https://user-images.githubusercontent.com/2439146/68724042-6e279380-0588-11ea-9c62-059fcb32de93.png">

**Comment by MatsMoll** [comment]
I see that I have not updated the README, but I think it should work If you change `StaticView` to `HTMLPage`.

**Comment by patchthecode** [comment]
OK. will close this issue.
Will use this project when things are up-to-date
thanks!
