### ISSUE TITLE
ForEach in StaticView

### ISSUE THREAD

**Issue by tonyarnold** [vapor-community/HTMLKit#9]
I've started spiking out using HTMLKit 2 in a Vapor 3 project, but I've hit a problem I can't figure out: how do I use `ForEach(…)` in a `StaticView`?

Given the following somewhat contrived example:

```swift
import Flash
import HTMLKit
import Vapor

struct FlashView: StaticView {
    let flashes: [Flash]

    var body: HTMLKit.View {
        return Div {
            ForEach(in: flashes) { flash in
                Div {
                    P { flash.message }
                }
                .class("message \(flash.kind)")
            }
        }
        .id("flash")
    }
}
```

I get the following error, pointing at the line with the `ForEach(…)` on it: 

```
Generic parameter 'Root' could not be inferred
```

**Comment by MatsMoll** [comment]
I have added a new test with your case, so it should work fine now. However, `StaticView` is now `HTMLPage` or `HTMLComponent` and `View` is changed to `HTML`.

Also, I do not know if this is intended, but using a `[Flash]` type will not make it dynamic on runtime, but will rather pre-render it with the given values. So if you want to make it dynamic, then you will need to consider using `TemplateValue<T, [Flash]>`.

**Comment by tonyarnold** [comment]
Thanks for the fix, and for the advice about using TemplateValue - love your work! 👍
