### ISSUE TITLE
missing data function on Input

### ISSUE THREAD

**Issue by onepayclick** [vapor-community/HTMLKit#91]
Hi, 

I was able to do this back on version 2.1.0
![image](https://user-images.githubusercontent.com/64233519/182974343-e040c71a-0a77-411c-8e8e-1f45321c9da7.png)

I searched around the codebase but it doesn't seem to be a way to add custom **data** attributes like 
**data-inputmask="'alias': 'phone'"**

**Comment by mattesmohr** [comment]
Thats true. The .data-* modifier does not exit anymore. Use the .custom modifier instead, like:

```swift
Input()
.custom(key: "data-inputmask", value: "\'alias\': \'phone\'")
```

That should do.
